# Generated by Django 3.1.5 on 2021-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.FileField(blank=True, upload_to='media/avatars/')),
            ],
        ),
    ]
