# Generated by Django 3.1.5 on 2021-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.FileField(upload_to='media/avatars/'),
        ),
    ]
